import './globals.css'
import { Inter, Roboto } from 'next/font/google'
import Navbar from '@/components/navbar/Navbar'
import Footer from '@/components/footer/Footer'
import { ThemeProvider } from '@/context/ThemeContext'
import { ContextProvider } from '@/context/ContextProvider'
import AuthProvider from '@/components/AuthProvider/AuthProvider'
import { usePathname } from 'next/navigation'

const roboto = Roboto({ subsets: ['latin'], weight: ['100', '300', '500', '700', '900'] })



export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        <ThemeProvider>
          <AuthProvider>
            <ContextProvider>
              <div className='container'>
                <Navbar />
                {children}
                <Footer />
              </div>
              </ContextProvider>
            </AuthProvider>
        </ThemeProvider>
      </body>
    </html>
  )
}
